/**
 * Read build metadata (hash + time) from dist/.build.json
 *
 * Generated by scripts/generate-build-hash.cjs at build time.
 * Used by --version, doctor, and daemon state to identify exact builds.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { projectPath } from '@/projectPath';

export interface BuildMeta {
  hash: string | undefined;
  time: string | undefined;
}

export function readBuildMeta(): BuildMeta {
  try {
    const metaPath = join(projectPath(), 'dist', '.build.json');
    if (!existsSync(metaPath)) {
      // Fallback: read legacy .hash file
      const hashPath = join(projectPath(), 'dist', '.hash');
      if (existsSync(hashPath)) {
        return { hash: readFileSync(hashPath, 'utf-8').trim(), time: undefined };
      }
      return { hash: undefined, time: undefined };
    }
    const raw = JSON.parse(readFileSync(metaPath, 'utf-8'));
    return { hash: raw.hash, time: raw.time };
  } catch {
    return { hash: undefined, time: undefined };
  }
}
