export type { LogSink } from './types.js'
export { MemorySink } from './memory.js'
export type { MemorySinkOptions, AsyncStorageLike } from './memory.js'
export { ConsoleSink } from './console.js'
export { RemoteSink } from './remote.js'
export type { RemoteSinkOptions } from './remote.js'
export { NewRelicBackend } from './backends/index.js'
export type { RemoteBackend, RemoteRequest, DeviceMetadata } from './backends/index.js'
