/**
 * Fingerprint configuration to keep runtimeVersion stable between local exports
 * and self-hosted CI builds after `expo prebuild`.
 */
module.exports = {
  // Ignore native directories generated by prebuild so local export and CI produce the same hash.
  ignorePaths: [
    'ios',
    'android',
  ],

};
