/**
 * Fingerprint configuration to ensure consistent runtime version between local and EAS builds.
 *
 * EAS builds include two additional sources not present locally:
 * 1. ios/ directory — generated by `expo prebuild` on EAS, ignored via .gitignore locally
 * 2. eas-environment-secrets/ file — GOOGLE_SERVICES_PLIST injected by EAS environment
 *
 * Without this config, EAS throws a hard error:
 *   "Runtime version calculated on local machine not equal to runtime version calculated during build."
 */
module.exports = {
  // Ignore native directories generated by prebuild — they exist on EAS but not locally
  ignorePaths: [
    'ios',
    'android',
    // EAS injects environment secrets as files outside the project root.
    // This path only exists on EAS workers, not locally.
    '../../../../eas-environment-secrets/**',
  ],

};
